name: 'Create patch release'

on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: 'Version tag'
        required: true
        type: string


jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Tag: ${{ inputs.versionTag }}"

#          git checkout -b release/<>
#          git push